#!/bin/sh
### This script used to control cleaner script which deltes old files, the script written in Scala(Scala pkg req.)##

DIR=/opt/init.d
DAEMON="/bin/sh $DIR/cleaner.sh /path/to 1>/var/log/cleaner.log"
DAEMON_NAME=cleaner

DAEMON_USER=root

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid

cleaner_pid() {
        echo `ps -fe | grep cleaner | grep -v grep | tr -s " "|cut -d" " -f2`
}

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    kill $(cleaner_pid)
    log_end_msg $?
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;
    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0

